# Generated by Django 2.2.6 on 2019-11-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wordcloud_pic_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
