# Generated by Django 2.2.6 on 2019-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_wordcloud_pic_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jd_order_id', models.BigIntegerField(default='0')),
                ('jd_skuid', models.BigIntegerField(default='0')),
                ('jd_sku_name', models.CharField(default='no name', max_length=200)),
                ('jd_sku_num', models.IntegerField(default='0')),
                ('jd_order_time', models.BigIntegerField(default='0')),
                ('as_done', models.BooleanField(default=False)),
            ],
        ),
    ]
